# Generated by Django 5.2 on 2025-04-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('last_updated', models.TextField(blank=True, null=True)),
                ('img_path', models.TextField(blank=True, null=True)),
                ('grorates', models.TextField(blank=True, db_column='groRates', null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
