# Generated by Django 5.2 on 2025-04-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flask_models', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
