# Generated by Django 5.1.6 on 2025-02-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
