# Generated by Django 5.2 on 2025-04-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='groRates',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
