# Generated by Django 5.2 on 2025-04-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_cartitems_product_id_alter_cartitems_grorates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='id',
            field=models.CharField(max_length=10000, primary_key=True, serialize=False),
        ),
    ]
