# Generated by Django 5.2 on 2025-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('groRates', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
