# Generated by Django 5.1.6 on 2025-02-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField()),
                ('productName', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('imgPath', models.URLField(max_length=150)),
            ],
        ),
    ]
