# Generated by Django 5.2 on 2025-04-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
