# Generated by Django 5.2 on 2025-04-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_product_image_path_alter_product_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodID',
        ),
        migrations.AddField(
            model_name='product',
            name='groID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
